### ISSUE TITLE
Platform: Adding comments deletes text or breaks the editor

### ISSUE THREAD

**Issue by Sebastian-ubs** [BiblioNexus-Foundation/scripture-editors#129]
When adding a comment to a text part with style type "no Style" it breaks the editor (looks like the comment can be created, but breaks on re-rendering).
When reopening the editor it is blanked out - and so the user is unable to recover from this!
![grafik](https://github.com/BiblioNexus-Foundation/scripture-editors/assets/141921979/7ec4878f-d3b4-40fe-9ea8-b1e441ec4551)
![grafik](https://github.com/BiblioNexus-Foundation/scripture-editors/assets/141921979/36ca5f4a-2185-4c53-aed8-dc0e93c70ee7)

Maybe related to some strange text that also gets added when adding text to other passages:
![Screenshot 2024-07-03 183517](https://github.com/BiblioNexus-Foundation/scripture-editors/assets/141921979/14820c3f-b7ac-4480-94cd-521e5520e8c3)
![Screenshot 2024-07-03 183532](https://github.com/BiblioNexus-Foundation/scripture-editors/assets/141921979/7bab9ff2-e73c-4b25-bd29-d8439133a867)

Deleting that comment does not delete the strange text. Manually deleting the text leaves the editor in some crazy state.
![Screenshot 2024-07-03 183612](https://github.com/BiblioNexus-Foundation/scripture-editors/assets/141921979/6db1f35d-b9d1-440a-8a3a-4454de5784f7)

looking into the .sfm file shows
> \v 2 You \zmsc-s |sid="xcyur" \know \zmsc-e |eid="xcyur" \, all da stuff da angel guys wen tell befo time was da trut, an was from God. If had peopo dat wen broke da Rules From God an neva lissen, God wen do da right ting wen he punish um fo da Rules dey wen broke.

root cause for https://github.com/paranext/paranext-core/issues/980

**Comment by irahopkinson** [comment]
@Sebastian-ubs I see this issue is when you are using the editor in P.B (Platform.Bible). Before you add comments to any PT project in P.B you will need to add a `custom.sty` file to the root of that PT project folder. You can copy that file from https://github.com/paranext/paranext-core/blob/main/assets-excluded/custom.sty

**Comment by Sebastian-ubs** [comment]
confirmed
