### ISSUE TITLE
Editor wipes out whenever there is text that it cannot handle

### ISSUE THREAD

**Issue by Sebastian-ubs** [BiblioNexus-Foundation/scripture-editors#132]
Implement robust error handling.
The editor should not wipe out whenever somebody enters a character that cannot be displayed or breaks the usfm structure.

Instead: the editor should
- ignore unknown character combinations
- display a warning message / banner, mentioning the line and character number of the bad character and the bad character (combination) itself
- ideally (not a must): highlight the bad character (combination)

How to reproduce:
1. find a heading section like `\s1` (this is displayed bold and centered in the editor)
2. enter a `\` after that to e.g. get
    > \s1 God Boy Mo Importan Den Moses\
3. unexpectedly: editor breaks and stays blank without more information

This even more so is a problem on loading text, as the editor will stay blank without any chance for the user to know why this is happening, because they did not just enter something they might remember.

**Comment by Sebastian-ubs** [comment]
also see https://github.com/BiblioNexus-Foundation/scripture-editors/issues/129 when it happens without the right custom.sty file.

**Comment by tjcouch-sil** [comment]
I believe this may be a problem only in Platform.Bible. See https://github.com/paranext/paranext-core/issues/1007 - is this the same issue? Can you reproduce the problem in the online editor preview https://codesandbox.io/p/github/BiblioNexus-Foundation/scripture-editors/main ?

**Comment by Sebastian-ubs** [comment]
You are right TJ, I am unable to reproduce in the shared editor sandbox. Thanks for creating an issue in platform. I am closing the issue here.
