### ISSUE TITLE
Not providing view options makes cursor reset after every input

### ISSUE THREAD

**Issue by tjcouch-sil** [BiblioNexus-Foundation/scripture-editors#134]
**Describe the bug**
If you don't provide view options, the editor only lets you input once at a time before it resets and puts your cursor back to the start of the line you're on.

**To Reproduce**

1. In the sandbox, remove the `view` property from the `options` object.
2. Put your cursor somewhere that isn't at the start of a line
3. Press any input key (character, backspace, etc)
4. Cursor resets to the start of the line

**Expected Behavior**
Either fill in the default options if they are not provided in a way that doesn't cause the editor to fully reload with every change (my personal preference and what I would expect to happen as "options" are usually providing things that differ from default), or make the `view` property mandatory (and please provide an example of how to provide the default settings in the TSDoc so we aren't guessing).

Thanks!

Tested on platform editor.

**Comment by irahopkinson** [comment]
Fixed in PR #143.
