### ISSUE TITLE
Upgrade `@xmldom/xmldom` to latest

### ISSUE THREAD

**Issue by tjcouch-sil** [BiblioNexus-Foundation/scripture-editors#201]
CodeQL is showing security issues in `@xmldom/xmldom` 0.8.10 (currently bundled with `@biblionexus-foundation/scripture-utilities` (0.0.4). I think they are false positives and have marked them as such. However, it would still be good to get this updated just in case.

https://github.com/paranext/paranext-core/security/code-scanning/410

![image](https://github.com/user-attachments/assets/1a5b5d83-3e78-415f-a5e2-19aee4bd55f1)

The latest `@xmldom/xmldom` does not have the code that is being flagged. Please upgrade when you have an opportunity :)

Thanks!

**Comment by irahopkinson** [comment]
@tjcouch-sil thanks for this reminder. I have attempted this previously while doing dependency updates but gave up at the time because there is a breaking change between v0.8 and v0.9. I'll need to look again.
