### ISSUE TITLE
The cursor jumps to the beginning of the verse on the first click

### ISSUE THREAD

**Issue by roopa0222** [BiblioNexus-Foundation/scripture-editors#217]
**Describe the bug**
The cursor jumps to the beginning of the verse on the first click

**To Reproduce**

1. Set the cursor at Psalms 1:3 at `prosper.`
2. Notice that on the first click, the cursor jumps to the beginning of the verse.

**Expected behavior**
The cursor should remain where it is clicked for the first time.

Note: The cursor stays in place on the second click.

https://github.com/user-attachments/assets/5f01df3e-08c6-4f0e-86de-ecec7b9ef7cb

**Comment by irahopkinson** [comment]
This is a regression after updating Lexical to v0.21.0.
